//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrolmentSystemClient.EnrolmentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enrolment", Namespace="http://schemas.datacontract.org/2004/07/EnrolmentSystem")]
    [System.SerializableAttribute()]
    public partial class Enrolment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((this.StudentIDField.Equals(value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnrolmentServiceReference.IEnrolmentService")]
    public interface IEnrolmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrolmentService/ViewEnrolment", ReplyAction="http://tempuri.org/IEnrolmentService/ViewEnrolmentResponse")]
        EnrolmentSystemClient.EnrolmentServiceReference.Enrolment[] ViewEnrolment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrolmentService/ViewEnrolment", ReplyAction="http://tempuri.org/IEnrolmentService/ViewEnrolmentResponse")]
        System.Threading.Tasks.Task<EnrolmentSystemClient.EnrolmentServiceReference.Enrolment[]> ViewEnrolmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrolmentService/AddEnrolment", ReplyAction="http://tempuri.org/IEnrolmentService/AddEnrolmentResponse")]
        void AddEnrolment(int StudentID, int CourseID, string Grade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrolmentService/AddEnrolment", ReplyAction="http://tempuri.org/IEnrolmentService/AddEnrolmentResponse")]
        System.Threading.Tasks.Task AddEnrolmentAsync(int StudentID, int CourseID, string Grade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnrolmentServiceChannel : EnrolmentSystemClient.EnrolmentServiceReference.IEnrolmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnrolmentServiceClient : System.ServiceModel.ClientBase<EnrolmentSystemClient.EnrolmentServiceReference.IEnrolmentService>, EnrolmentSystemClient.EnrolmentServiceReference.IEnrolmentService {
        
        public EnrolmentServiceClient() {
        }
        
        public EnrolmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnrolmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrolmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrolmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EnrolmentSystemClient.EnrolmentServiceReference.Enrolment[] ViewEnrolment() {
            return base.Channel.ViewEnrolment();
        }
        
        public System.Threading.Tasks.Task<EnrolmentSystemClient.EnrolmentServiceReference.Enrolment[]> ViewEnrolmentAsync() {
            return base.Channel.ViewEnrolmentAsync();
        }
        
        public void AddEnrolment(int StudentID, int CourseID, string Grade) {
            base.Channel.AddEnrolment(StudentID, CourseID, Grade);
        }
        
        public System.Threading.Tasks.Task AddEnrolmentAsync(int StudentID, int CourseID, string Grade) {
            return base.Channel.AddEnrolmentAsync(StudentID, CourseID, Grade);
        }
    }
}
